
spring:
  # POSTGERSQL
  datasource:
    url: jdbc:postgresql://localhost:15432/yhk_querydsl
    username: dboopg
    password: dboopg
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
#        jpql 을 comment로 보여줌
#        use_sql_comments: true
  logging.level:
    org.hibernate.SQL: debug